# Generated by Django 5.0 on 2024-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiffin', '0002_user_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
