# Generated by Django 5.0 on 2024-06-02 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiffin', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idcity', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'City',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=45)),
                ('delivery_charges', models.IntegerField()),
                ('city_name', models.ForeignKey(db_column='_idcity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tiffin.city')),
            ],
            options={
                'db_table': 'Area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('contact', models.CharField(max_length=10, null=True, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tiffin.city')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
