# Generated by Django 5.0 on 2024-06-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiffin', '0006_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('MenuItem_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'MenuItem',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='Tiffin.month'),
        ),
    ]
