# Generated by Django 5.0.7 on 2024-07-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiffin', '0007_menuitem_alter_day_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_id',
            field=models.ForeignKey(db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tiffin.area'),
        ),
    ]
